// Fork Awesome icon defines for Dear ImGui.
// Originally generated with https://github.com/aiekick/ImGuiFontStudio
// Based on https://github.com/juliettef/IconFontCppHeaders
//
// DIFF: u8"\uXXXX" literals replaced with plain char UTF-8 byte escapes.
//       Rationale:
//         - C++20 makes u8"" a const char8_t*, which will not implicitly
//           convert to const char* (ImGui APIs take const char*).
//         - Plain "\xEF\x81\x82" literals are raw bytes and are therefore
//           independent of the compiler's execution charset (/utf-8, code
//           page 1252, etc). No source-file encoding requirement either:
//           this header is pure 7-bit ASCII.
//       Byte sequences are the exact UTF-8 encodings of the original
//       codepoints, so rendering behaviour is unchanged.

#pragma once

#define FONT_ICON_BUFFER_NAME_FK FK_compressed_data_base85
#define FONT_ICON_BUFFER_SIZE_FK 0xe420

#define ICON_MIN_FK 0xf001
#define ICON_MAX_FK 0xf32f

#define ICON_FK_ADJUST                 "\xef\x81\x82" // U+f042
#define ICON_FK_ALIGN_CENTER           "\xef\x80\xb7" // U+f037
#define ICON_FK_ALIGN_JUSTIFY          "\xef\x80\xb9" // U+f039
#define ICON_FK_ALIGN_LEFT             "\xef\x80\xb6" // U+f036
#define ICON_FK_ALIGN_RIGHT            "\xef\x80\xb8" // U+f038
#define ICON_FK_ANCHOR                 "\xef\x84\xbd" // U+f13d
#define ICON_FK_ANDROID                "\xef\x85\xbb" // U+f17b
#define ICON_FK_ANGLE_DOUBLE_DOWN      "\xef\x84\x83" // U+f103
#define ICON_FK_ANGLE_DOUBLE_LEFT      "\xef\x84\x80" // U+f100
#define ICON_FK_ANGLE_DOUBLE_RIGHT     "\xef\x84\x81" // U+f101
#define ICON_FK_ANGLE_DOUBLE_UP        "\xef\x84\x82" // U+f102
#define ICON_FK_ANGLE_DOWN             "\xef\x84\x87" // U+f107
#define ICON_FK_ANGLE_LEFT             "\xef\x84\x84" // U+f104
#define ICON_FK_ANGLE_RIGHT            "\xef\x84\x85" // U+f105
#define ICON_FK_ANGLE_UP               "\xef\x84\x86" // U+f106
#define ICON_FK_APPLE                  "\xef\x85\xb9" // U+f179
#define ICON_FK_ARCHIVE                "\xef\x86\x87" // U+f187
#define ICON_FK_ARROW_CIRCLE_DOWN      "\xef\x82\xab" // U+f0ab
#define ICON_FK_ARROW_CIRCLE_LEFT      "\xef\x82\xa8" // U+f0a8
#define ICON_FK_ARROW_CIRCLE_RIGHT     "\xef\x82\xa9" // U+f0a9
#define ICON_FK_ARROW_CIRCLE_UP        "\xef\x82\xaa" // U+f0aa
#define ICON_FK_ARROW_DOWN             "\xef\x81\xa3" // U+f063
#define ICON_FK_ARROW_LEFT             "\xef\x81\xa0" // U+f060
#define ICON_FK_ARROW_RIGHT            "\xef\x81\xa1" // U+f061
#define ICON_FK_ARROW_UP               "\xef\x81\xa2" // U+f062
#define ICON_FK_ASTERISK               "\xef\x81\xa9" // U+f069
#define ICON_FK_AT                     "\xef\x87\xba" // U+f1fa
#define ICON_FK_BACKWARD               "\xef\x81\x8a" // U+f04a
#define ICON_FK_BAN                    "\xef\x81\x9e" // U+f05e
#define ICON_FK_BARCODE                "\xef\x80\xaa" // U+f02a
#define ICON_FK_BARS                   "\xef\x83\x89" // U+f0c9
#define ICON_FK_BATTERY                "\xef\x89\x80" // U+f240
#define ICON_FK_BATTERY_EMPTY          "\xef\x89\x84" // U+f244
#define ICON_FK_BATTERY_HALF           "\xef\x89\x82" // U+f242
#define ICON_FK_BATTERY_QUARTER        "\xef\x89\x83" // U+f243
#define ICON_FK_BATTERY_THREE_QUARTERS "\xef\x89\x81" // U+f241
#define ICON_FK_BEER                   "\xef\x83\xbc" // U+f0fc
#define ICON_FK_BELL                   "\xef\x83\xb3" // U+f0f3
#define ICON_FK_BELL_RINGING           "\xef\x8c\xad" // U+f32d
#define ICON_FK_BELL_SLASH             "\xef\x87\xb7" // U+f1f7
#define ICON_FK_BINOCULARS             "\xef\x87\xa5" // U+f1e5
#define ICON_FK_BIRTHDAY_CAKE          "\xef\x87\xbd" // U+f1fd
#define ICON_FK_BLUETOOTH              "\xef\x8a\x93" // U+f293
#define ICON_FK_BOLD                   "\xef\x80\xb2" // U+f032
#define ICON_FK_BOLT                   "\xef\x83\xa7" // U+f0e7
#define ICON_FK_BOOK                   "\xef\x80\xad" // U+f02d
#define ICON_FK_BOOKMARK               "\xef\x82\x97" // U+f097
#define ICON_FK_BRIEFCASE              "\xef\x82\xb1" // U+f0b1
#define ICON_FK_BUG                    "\xef\x86\x88" // U+f188
#define ICON_FK_BUILDING               "\xef\x83\xb7" // U+f0f7
#define ICON_FK_BULLHORN               "\xef\x82\xa1" // U+f0a1
#define ICON_FK_BULLSEYE               "\xef\x85\x80" // U+f140
#define ICON_FK_CALENDAR               "\xef\x81\xb3" // U+f073
#define ICON_FK_CALENDAR_EMPTY         "\xef\x84\xb3" // U+f133
#define ICON_FK_CAMERA                 "\xef\x80\xb0" // U+f030
#define ICON_FK_CAMERA_RETRO           "\xef\x82\x83" // U+f083
#define ICON_FK_CANCEL                 "\xef\x80\x8d" // U+f00d
#define ICON_FK_CANCEL_CIRCLE          "\xef\x81\x97" // U+f057
#define ICON_FK_CARET_DOWN             "\xef\x83\x97" // U+f0d7
#define ICON_FK_CARET_LEFT             "\xef\x83\x99" // U+f0d9
#define ICON_FK_CARET_RIGHT            "\xef\x83\x9a" // U+f0da
#define ICON_FK_CARET_UP               "\xef\x83\x98" // U+f0d8
#define ICON_FK_CERTIFICATE            "\xef\x82\xa3" // U+f0a3
#define ICON_FK_CHART_AREA             "\xef\x87\xbe" // U+f1fe
#define ICON_FK_CHART_BAR              "\xef\x82\x80" // U+f080
#define ICON_FK_CHART_LINE             "\xef\x88\x81" // U+f201
#define ICON_FK_CHART_PIE              "\xef\x88\x80" // U+f200
#define ICON_FK_CHEVRON_CIRCLE_DOWN    "\xef\x84\xba" // U+f13a
#define ICON_FK_CHEVRON_CIRCLE_LEFT    "\xef\x84\xb7" // U+f137
#define ICON_FK_CHEVRON_CIRCLE_RIGHT   "\xef\x84\xb8" // U+f138
#define ICON_FK_CHEVRON_CIRCLE_UP      "\xef\x84\xb9" // U+f139
#define ICON_FK_CHEVRON_DOWN           "\xef\x81\xb8" // U+f078
#define ICON_FK_CHEVRON_LEFT           "\xef\x81\x93" // U+f053
#define ICON_FK_CHEVRON_RIGHT          "\xef\x81\x94" // U+f054
#define ICON_FK_CHEVRON_UP             "\xef\x81\xb7" // U+f077
#define ICON_FK_CIRCLE                 "\xef\x84\x91" // U+f111
#define ICON_FK_CIRCLE_EMPTY           "\xef\x84\x8c" // U+f10c
#define ICON_FK_CLIPBOARD              "\xef\x83\xaa" // U+f0ea
#define ICON_FK_CLOCK                  "\xef\x80\x97" // U+f017
#define ICON_FK_CLONE                  "\xef\x89\x8d" // U+f24d
#define ICON_FK_CLOUD                  "\xef\x83\x82" // U+f0c2
#define ICON_FK_CLOUD_DOWNLOAD         "\xef\x83\xad" // U+f0ed
#define ICON_FK_CLOUD_UPLOAD           "\xef\x83\xae" // U+f0ee
#define ICON_FK_CODE                   "\xef\x84\xa1" // U+f121
#define ICON_FK_CODE_FORK              "\xef\x84\xa6" // U+f126
#define ICON_FK_COFFEE                 "\xef\x83\xb4" // U+f0f4
#define ICON_FK_COG                    "\xef\x80\x93" // U+f013
#define ICON_FK_COGS                   "\xef\x82\x85" // U+f085
#define ICON_FK_COLUMNS                "\xef\x83\x9b" // U+f0db
#define ICON_FK_COMMENT                "\xef\x81\xb5" // U+f075
#define ICON_FK_COMMENTING             "\xef\x89\xba" // U+f27a
#define ICON_FK_COMMENTS               "\xef\x82\x86" // U+f086
#define ICON_FK_COMPASS                "\xef\x85\x8e" // U+f14e
#define ICON_FK_COPY                   "\xef\x83\x85" // U+f0c5
#define ICON_FK_COPYRIGHT              "\xef\x87\xb9" // U+f1f9
#define ICON_FK_CROP                   "\xef\x84\xa5" // U+f125
#define ICON_FK_CROSSHAIRS             "\xef\x81\x9b" // U+f05b
#define ICON_FK_CUT                    "\xef\x83\x84" // U+f0c4
#define ICON_FK_DASHBOARD              "\xef\x83\xa4" // U+f0e4
#define ICON_FK_DESKTOP                "\xef\x84\x88" // U+f108
#define ICON_FK_DIAMOND                "\xef\x88\x99" // U+f219
#define ICON_FK_DOT_CIRCLE             "\xef\x86\x92" // U+f192
#define ICON_FK_DOWNLOAD               "\xef\x80\x99" // U+f019
#define ICON_FK_EJECT                  "\xef\x81\x92" // U+f052
#define ICON_FK_ELLIPSIS_HORIZONTAL    "\xef\x85\x81" // U+f141
#define ICON_FK_ELLIPSIS_VERTICAL      "\xef\x85\x82" // U+f142
#define ICON_FK_ENVELOPE               "\xef\x80\x83" // U+f003
#define ICON_FK_EXCHANGE               "\xef\x83\xac" // U+f0ec
#define ICON_FK_EXCLAMATION            "\xef\x84\xaa" // U+f12a
#define ICON_FK_EXCLAMATION_CIRCLE     "\xef\x81\xaa" // U+f06a
#define ICON_FK_EXTERNAL_LINK          "\xef\x82\x8e" // U+f08e
#define ICON_FK_EYE                    "\xef\x81\xae" // U+f06e
#define ICON_FK_EYE_SLASH              "\xef\x81\xb0" // U+f070
#define ICON_FK_EYEDROPPER             "\xef\x87\xbb" // U+f1fb
#define ICON_FK_FAST_BACKWARD          "\xef\x81\x89" // U+f049
#define ICON_FK_FAST_FORWARD           "\xef\x81\x90" // U+f050
#define ICON_FK_FEMALE                 "\xef\x86\x82" // U+f182
#define ICON_FK_FILE                   "\xef\x80\x96" // U+f016
#define ICON_FK_FILE_ARCHIVE           "\xef\x87\x86" // U+f1c6
#define ICON_FK_FILE_AUDIO             "\xef\x87\x87" // U+f1c7
#define ICON_FK_FILE_CODE              "\xef\x87\x89" // U+f1c9
#define ICON_FK_FILE_IMAGE             "\xef\x87\x85" // U+f1c5
#define ICON_FK_FILE_TEXT              "\xef\x83\xb6" // U+f0f6
#define ICON_FK_FILE_VIDEO             "\xef\x87\x88" // U+f1c8
#define ICON_FK_FILM                   "\xef\x80\x88" // U+f008
#define ICON_FK_FILTER                 "\xef\x82\xb0" // U+f0b0
#define ICON_FK_FIRE                   "\xef\x81\xad" // U+f06d
#define ICON_FK_FIRE_EXTINGUISHER      "\xef\x84\xb4" // U+f134
#define ICON_FK_FLAG                   "\xef\x80\xa4" // U+f024
#define ICON_FK_FLAG_CHECKERED         "\xef\x84\x9e" // U+f11e
#define ICON_FK_FLASK                  "\xef\x83\x83" // U+f0c3
#define ICON_FK_FLOPPY                 "\xef\x83\x87" // U+f0c7
#define ICON_FK_FOLDER                 "\xef\x84\x94" // U+f114
#define ICON_FK_FOLDER_OPEN            "\xef\x84\x95" // U+f115
#define ICON_FK_FONT                   "\xef\x80\xb1" // U+f031
#define ICON_FK_FOOD                   "\xef\x83\xb5" // U+f0f5
#define ICON_FK_FORWARD                "\xef\x81\x8e" // U+f04e
#define ICON_FK_FULLSCREEN             "\xef\x82\xb2" // U+f0b2
#define ICON_FK_GAMEPAD                "\xef\x84\x9b" // U+f11b
#define ICON_FK_GIFT                   "\xef\x81\xab" // U+f06b
#define ICON_FK_GITHUB                 "\xef\x82\x9b" // U+f09b
#define ICON_FK_GLOBE                  "\xef\x82\xac" // U+f0ac
#define ICON_FK_GRADUATION_CAP         "\xef\x86\x9d" // U+f19d
#define ICON_FK_HAND_DOWN              "\xef\x82\xa7" // U+f0a7
#define ICON_FK_HAND_LEFT              "\xef\x82\xa5" // U+f0a5
#define ICON_FK_HAND_RIGHT             "\xef\x82\xa4" // U+f0a4
#define ICON_FK_HAND_UP                "\xef\x82\xa6" // U+f0a6
#define ICON_FK_HDD                    "\xef\x82\xa0" // U+f0a0
#define ICON_FK_HEADPHONES             "\xef\x80\xa5" // U+f025
#define ICON_FK_HEART                  "\xef\x80\x84" // U+f004
#define ICON_FK_HEART_EMPTY            "\xef\x82\x8a" // U+f08a
#define ICON_FK_HEARTBEAT              "\xef\x88\x9e" // U+f21e
#define ICON_FK_HISTORY                "\xef\x87\x9a" // U+f1da
#define ICON_FK_HOME                   "\xef\x80\x95" // U+f015
#define ICON_FK_HOURGLASS              "\xef\x89\x94" // U+f254
#define ICON_FK_HOURGLASS_EMPTY        "\xef\x89\x90" // U+f250
#define ICON_FK_HOURGLASS_END          "\xef\x89\x93" // U+f253
#define ICON_FK_HOURGLASS_HALF         "\xef\x89\x92" // U+f252
#define ICON_FK_HOURGLASS_START        "\xef\x89\x91" // U+f251
#define ICON_FK_INBOX                  "\xef\x80\x9c" // U+f01c
#define ICON_FK_INDENT_LEFT            "\xef\x80\xbb" // U+f03b
#define ICON_FK_INDENT_RIGHT           "\xef\x80\xbc" // U+f03c
#define ICON_FK_INFO                   "\xef\x84\xa9" // U+f129
#define ICON_FK_INFO_CIRCLE            "\xef\x81\x9a" // U+f05a
#define ICON_FK_ITALIC                 "\xef\x80\xb3" // U+f033
#define ICON_FK_KEY                    "\xef\x82\x84" // U+f084
#define ICON_FK_KEYBOARD               "\xef\x84\x9c" // U+f11c
#define ICON_FK_LANGUAGE               "\xef\x86\xab" // U+f1ab
#define ICON_FK_LAPTOP                 "\xef\x84\x89" // U+f109
#define ICON_FK_LEAF                   "\xef\x81\xac" // U+f06c
#define ICON_FK_LEGAL                  "\xef\x83\xa3" // U+f0e3
#define ICON_FK_LEVEL_DOWN             "\xef\x85\x89" // U+f149
#define ICON_FK_LEVEL_UP               "\xef\x85\x88" // U+f148
#define ICON_FK_LIGHT_BULB             "\xef\x83\xab" // U+f0eb
#define ICON_FK_LINK                   "\xef\x83\x81" // U+f0c1
#define ICON_FK_LINUX                  "\xef\x85\xbc" // U+f17c
#define ICON_FK_LIST                   "\xef\x80\xba" // U+f03a
#define ICON_FK_LIST_ALT               "\xef\x80\xa2" // U+f022
#define ICON_FK_LIST_OL                "\xef\x83\x8b" // U+f0cb
#define ICON_FK_LIST_UL                "\xef\x83\x8a" // U+f0ca
#define ICON_FK_LOCATION_ARROW         "\xef\x84\xa4" // U+f124
#define ICON_FK_LOCK                   "\xef\x80\xa3" // U+f023
#define ICON_FK_LONG_ARROW_DOWN        "\xef\x85\xb5" // U+f175
#define ICON_FK_LONG_ARROW_LEFT        "\xef\x85\xb7" // U+f177
#define ICON_FK_LONG_ARROW_RIGHT       "\xef\x85\xb8" // U+f178
#define ICON_FK_LONG_ARROW_UP          "\xef\x85\xb6" // U+f176
#define ICON_FK_MAGIC                  "\xef\x83\x90" // U+f0d0
#define ICON_FK_MAGNET                 "\xef\x81\xb6" // U+f076
#define ICON_FK_MALE                   "\xef\x86\x83" // U+f183
#define ICON_FK_MAP_MARKER             "\xef\x81\x81" // U+f041
#define ICON_FK_MEDKIT                 "\xef\x83\xba" // U+f0fa
#define ICON_FK_MICROPHONE             "\xef\x84\xb0" // U+f130
#define ICON_FK_MICROPHONE_SLASH       "\xef\x84\xb1" // U+f131
#define ICON_FK_MINUS                  "\xef\x81\xa8" // U+f068
#define ICON_FK_MINUS_CIRCLE           "\xef\x81\x96" // U+f056
#define ICON_FK_MINUS_SQUARE           "\xef\x85\x86" // U+f146
#define ICON_FK_MOBILE                 "\xef\x84\x8b" // U+f10b
#define ICON_FK_MOON                   "\xef\x8c\xa8" // U+f328
#define ICON_FK_MOON_EMPTY             "\xef\x86\x86" // U+f186
#define ICON_FK_MOUSE_POINTER          "\xef\x89\x85" // U+f245
#define ICON_FK_MOVE                   "\xef\x81\x87" // U+f047
#define ICON_FK_MUSIC                  "\xef\x80\x81" // U+f001
#define ICON_FK_OFF                    "\xef\x80\x91" // U+f011
#define ICON_FK_OK                     "\xef\x80\x8c" // U+f00c
#define ICON_FK_OK_CIRCLE              "\xef\x81\x98" // U+f058
#define ICON_FK_OK_SQUARE              "\xef\x85\x8a" // U+f14a
#define ICON_FK_PAINT_BRUSH            "\xef\x87\xbc" // U+f1fc
#define ICON_FK_PAPER_CLIP             "\xef\x83\x86" // U+f0c6
#define ICON_FK_PAPER_PLANE            "\xef\x87\x98" // U+f1d8
#define ICON_FK_PAUSE                  "\xef\x81\x8c" // U+f04c
#define ICON_FK_PAUSE_CIRCLE           "\xef\x8a\x8b" // U+f28b
#define ICON_FK_PAUSE_CIRCLE_ALT       "\xef\x8a\x8c" // U+f28c
#define ICON_FK_PENCIL                 "\xef\x81\x80" // U+f040
#define ICON_FK_PENCIL_SQUARE          "\xef\x85\x8b" // U+f14b
#define ICON_FK_PICTURE                "\xef\x80\xbe" // U+f03e
#define ICON_FK_PLANE                  "\xef\x81\xb2" // U+f072
#define ICON_FK_PLAY                   "\xef\x81\x8b" // U+f04b
#define ICON_FK_PLAY_CIRCLE            "\xef\x85\x84" // U+f144
#define ICON_FK_PLUG                   "\xef\x87\xa6" // U+f1e6
#define ICON_FK_PLUS                   "\xef\x81\xa7" // U+f067
#define ICON_FK_PLUS_CIRCLE            "\xef\x81\x95" // U+f055
#define ICON_FK_PLUS_SQUARE            "\xef\x83\xbe" // U+f0fe
#define ICON_FK_PRINT                  "\xef\x80\xaf" // U+f02f
#define ICON_FK_PUSHPIN                "\xef\x82\x8d" // U+f08d
#define ICON_FK_PUZZLE_PIECE           "\xef\x84\xae" // U+f12e
#define ICON_FK_QRCODE                 "\xef\x80\xa9" // U+f029
#define ICON_FK_QUESTION               "\xef\x84\xa8" // U+f128
#define ICON_FK_QUESTION_CIRCLE        "\xef\x81\x99" // U+f059
#define ICON_FK_QUOTE_LEFT             "\xef\x84\x8d" // U+f10d
#define ICON_FK_QUOTE_RIGHT            "\xef\x84\x8e" // U+f10e
#define ICON_FK_RANDOM                 "\xef\x81\xb4" // U+f074
#define ICON_FK_REFRESH                "\xef\x80\xa1" // U+f021
#define ICON_FK_REGISTERED             "\xef\x89\x9d" // U+f25d
#define ICON_FK_REPEAT                 "\xef\x80\x9e" // U+f01e
#define ICON_FK_REPLY                  "\xef\x84\x92" // U+f112
#define ICON_FK_REPLY_ALL              "\xef\x84\xa2" // U+f122
#define ICON_FK_RESIZE_COMPRESS        "\xef\x81\xa6" // U+f066
#define ICON_FK_RESIZE_EXPAND          "\xef\x81\xa5" // U+f065
#define ICON_FK_RESIZE_HORIZONTAL      "\xef\x81\xbe" // U+f07e
#define ICON_FK_RESIZE_VERTICAL        "\xef\x81\xbd" // U+f07d
#define ICON_FK_RETWEET                "\xef\x81\xb9" // U+f079
#define ICON_FK_ROAD                   "\xef\x80\x98" // U+f018
#define ICON_FK_ROCKET                 "\xef\x84\xb5" // U+f135
#define ICON_FK_RSS                    "\xef\x82\x9e" // U+f09e
#define ICON_FK_SEARCH                 "\xef\x80\x82" // U+f002
#define ICON_FK_SEARCH_MINUS           "\xef\x80\x90" // U+f010
#define ICON_FK_SEARCH_PLUS            "\xef\x80\x8e" // U+f00e
#define ICON_FK_SERVER                 "\xef\x88\xb3" // U+f233
#define ICON_FK_SHARE                  "\xef\x81\xa4" // U+f064
#define ICON_FK_SHARE_ALT              "\xef\x87\xa0" // U+f1e0
#define ICON_FK_SHARE_ALT_SQUARE       "\xef\x87\xa1" // U+f1e1
#define ICON_FK_SHARE_SQUARE           "\xef\x85\x8d" // U+f14d
#define ICON_FK_SHIELD                 "\xef\x84\xb2" // U+f132
#define ICON_FK_SHOPPING_CART          "\xef\x81\xba" // U+f07a
#define ICON_FK_SIGN_IN                "\xef\x82\x90" // U+f090
#define ICON_FK_SIGN_OUT               "\xef\x82\x8b" // U+f08b
#define ICON_FK_SIGNAL                 "\xef\x80\x92" // U+f012
#define ICON_FK_SITEMAP                "\xef\x83\xa8" // U+f0e8
#define ICON_FK_SLIDERS                "\xef\x87\x9e" // U+f1de
#define ICON_FK_SMILEY                 "\xef\x84\x98" // U+f118
#define ICON_FK_SMILEY_FROWN           "\xef\x84\x99" // U+f119
#define ICON_FK_SMILEY_MEH             "\xef\x84\x9a" // U+f11a
#define ICON_FK_SORT                   "\xef\x83\x9c" // U+f0dc
#define ICON_FK_SORT_ALPHABET_ASC      "\xef\x85\x9d" // U+f15d
#define ICON_FK_SORT_ALPHABET_DESC     "\xef\x85\x9e" // U+f15e
#define ICON_FK_SORT_AMOUNT_ASC        "\xef\x85\xa0" // U+f160
#define ICON_FK_SORT_AMOUNT_DESC       "\xef\x85\xa1" // U+f161
#define ICON_FK_SORT_ASC               "\xef\x83\x9e" // U+f0de
#define ICON_FK_SORT_DESC              "\xef\x83\x9d" // U+f0dd
#define ICON_FK_SORT_NUMERIC_ASC       "\xef\x85\xa2" // U+f162
#define ICON_FK_SORT_NUMERIC_DESC      "\xef\x85\xa3" // U+f163
#define ICON_FK_SQUARE                 "\xef\x83\x88" // U+f0c8
#define ICON_FK_SQUARE_EMPTY           "\xef\x82\x96" // U+f096
#define ICON_FK_STAR                   "\xef\x80\x85" // U+f005
#define ICON_FK_STAR_EMPTY             "\xef\x80\x86" // U+f006
#define ICON_FK_STAR_HALF              "\xef\x84\xa3" // U+f123
#define ICON_FK_STEAM                  "\xef\x86\xb6" // U+f1b6
#define ICON_FK_STEAM_SQUARE           "\xef\x86\xb7" // U+f1b7
#define ICON_FK_STEP_BACKWARD          "\xef\x81\x88" // U+f048
#define ICON_FK_STEP_FORWARD           "\xef\x81\x91" // U+f051
#define ICON_FK_STETHOSCOPE            "\xef\x83\xb1" // U+f0f1
#define ICON_FK_STICKY_NOTE            "\xef\x89\x8a" // U+f24a
#define ICON_FK_STOP                   "\xef\x81\x8d" // U+f04d
#define ICON_FK_STOP_CIRCLE            "\xef\x8a\x8d" // U+f28d
#define ICON_FK_STOP_CIRCLE_ALT        "\xef\x8a\x8e" // U+f28e
#define ICON_FK_STRIKETHROUGH          "\xef\x83\x8c" // U+f0cc
#define ICON_FK_SUITCASE               "\xef\x83\xb2" // U+f0f2
#define ICON_FK_SUN                    "\xef\x8c\xa9" // U+f329
#define ICON_FK_SUN_EMPTY              "\xef\x86\x85" // U+f185
#define ICON_FK_TABLE                  "\xef\x83\x8e" // U+f0ce
#define ICON_FK_TABLET                 "\xef\x84\x8a" // U+f10a
#define ICON_FK_TAG                    "\xef\x80\xab" // U+f02b
#define ICON_FK_TAGS                   "\xef\x80\xac" // U+f02c
#define ICON_FK_TASKS                  "\xef\x82\xae" // U+f0ae
#define ICON_FK_TELEVISION             "\xef\x89\xac" // U+f26c
#define ICON_FK_TERMINAL               "\xef\x84\xa0" // U+f120
#define ICON_FK_TH                     "\xef\x80\x8a" // U+f00a
#define ICON_FK_TH_LARGE               "\xef\x80\x89" // U+f009
#define ICON_FK_TH_LIST                "\xef\x80\x8b" // U+f00b
#define ICON_FK_THUMBS_DOWN            "\xef\x82\x88" // U+f088
#define ICON_FK_THUMBS_UP              "\xef\x82\x87" // U+f087
#define ICON_FK_TICKET                 "\xef\x85\x85" // U+f145
#define ICON_FK_TINT                   "\xef\x81\x83" // U+f043
#define ICON_FK_TOGGLE_OFF             "\xef\x88\x84" // U+f204
#define ICON_FK_TOGGLE_ON              "\xef\x88\x85" // U+f205
#define ICON_FK_TRADEMARK              "\xef\x89\x9c" // U+f25c
#define ICON_FK_TRASH                  "\xef\x87\xb8" // U+f1f8
#define ICON_FK_TRASH_ALT              "\xef\x80\x94" // U+f014
#define ICON_FK_TROPHY                 "\xef\x82\x91" // U+f091
#define ICON_FK_TRUCK                  "\xef\x83\x91" // U+f0d1
#define ICON_FK_UMBRELLA               "\xef\x83\xa9" // U+f0e9
#define ICON_FK_UNDERLINE              "\xef\x83\x8d" // U+f0cd
#define ICON_FK_UNDO                   "\xef\x83\xa2" // U+f0e2
#define ICON_FK_UNIVERSITY             "\xef\x86\x9c" // U+f19c
#define ICON_FK_UNLINK                 "\xef\x84\xa7" // U+f127
#define ICON_FK_UNLOCK                 "\xef\x82\x9c" // U+f09c
#define ICON_FK_UPLOAD                 "\xef\x82\x93" // U+f093
#define ICON_FK_USB                    "\xef\x8a\x87" // U+f287
#define ICON_FK_USER                   "\xef\x80\x87" // U+f007
#define ICON_FK_USER_EMPTY             "\xef\x8b\x80" // U+f2c0
#define ICON_FK_USER_SECRET            "\xef\x88\x9b" // U+f21b
#define ICON_FK_USERS                  "\xef\x83\x80" // U+f0c0
#define ICON_FK_VIDEO_CAMERA           "\xef\x80\xbd" // U+f03d
#define ICON_FK_VOLUME_DOWN            "\xef\x80\xa7" // U+f027
#define ICON_FK_VOLUME_MUTE            "\xef\x8c\xaf" // U+f32f
#define ICON_FK_VOLUME_OFF             "\xef\x80\xa6" // U+f026
#define ICON_FK_VOLUME_UP              "\xef\x80\xa8" // U+f028
#define ICON_FK_WARNING                "\xef\x81\xb1" // U+f071
#define ICON_FK_WHEELCHAIR             "\xef\x86\x93" // U+f193
#define ICON_FK_WINDOW_CLOSE           "\xef\x8b\x93" // U+f2d3
#define ICON_FK_WINDOW_MAXIMIZE        "\xef\x8b\x90" // U+f2d0
#define ICON_FK_WINDOW_MINIMIZE        "\xef\x8b\x91" // U+f2d1
#define ICON_FK_WINDOW_RESTORE         "\xef\x8b\x92" // U+f2d2
#define ICON_FK_WINDOWS                "\xef\x85\xba" // U+f17a
#define ICON_FK_WRENCH                 "\xef\x82\xad" // U+f0ad