#include "BlitterPack.byte.scalar.h"

BlitterPack8Scalar::BlitterPack8Scalar(BYTE* pPaletteData, BYTE* pRemapData, BYTE** ppCurrentZRemap)
	: BlitterPlainXlat(pPaletteData)
	, BlitterTransXlat(pPaletteData)
	, BlitterTransRemapDest(pRemapData)
	, BlitterTransZRemapXlat(ppCurrentZRemap, pPaletteData)
	, BlitterTransRemapXlat75(pRemapData, pPaletteData)
	, BlitterTransRemapXlat50(pRemapData, pPaletteData)
	, BlitterTransRemapXlat25(pRemapData, pPaletteData)
	, RleBlitterTransXlat(pPaletteData)
	, RleBlitterTransRemapDest(pRemapData)
	, RleBlitterTransZRemapXlat(ppCurrentZRemap, pPaletteData)
	, RleBlitterTransRemapXlat75(pRemapData, pPaletteData)
	, RleBlitterTransRemapXlat50(pRemapData, pPaletteData)
	, RleBlitterTransRemapXlat25(pRemapData, pPaletteData)
	, RleBlitterTransXlatZRead(pPaletteData)
	, RleBlitterTransRemapDestZRead(pRemapData)
	, RleBlitterTransZRemapXlatZRead(ppCurrentZRemap, pPaletteData)
	, RleBlitterTransRemapXlatZRead75(pRemapData, pPaletteData)
	, RleBlitterTransRemapXlatZRead50(pRemapData, pPaletteData)
	, RleBlitterTransRemapXlatZRead25(pRemapData, pPaletteData)
	, RleBlitterTransXlatZReadWrite(pPaletteData)
	, RleBlitterTransRemapDestZReadWrite(pRemapData)
	, RleBlitterTransZRemapXlatZReadWrite(ppCurrentZRemap, pPaletteData)
	, RleBlitterTransRemapXlatZReadWrite75(pRemapData, pPaletteData)
	, RleBlitterTransRemapXlatZReadWrite50(pRemapData, pPaletteData)
	, RleBlitterTransRemapXlatZReadWrite25(pRemapData, pPaletteData)
{}