#include "BlitterPack.byte.avx512.h"

BlitterPack8AVX512::BlitterPack8AVX512(BYTE* paletteData, BYTE* remapData, BYTE** currentZRemap)
	: BlitterPlainXlat(paletteData)
	, BlitterTransXlat(paletteData)
	, BlitterTransRemapDest(remapData)
	, BlitterTransZRemapXlat(currentZRemap, paletteData)
	, BlitterTransRemapXlat75(remapData, paletteData)
	, BlitterTransRemapXlat50(remapData, paletteData)
	, BlitterTransRemapXlat25(remapData, paletteData)
	, RleBlitterTransXlat(paletteData)
	, RleBlitterTransRemapDest(remapData)
	, RleBlitterTransZRemapXlat(currentZRemap, paletteData)
	, RleBlitterTransRemapXlat75(remapData, paletteData)
	, RleBlitterTransRemapXlat50(remapData, paletteData)
	, RleBlitterTransRemapXlat25(remapData, paletteData)
	, RleBlitterTransXlatZRead(paletteData)
	, RleBlitterTransRemapDestZRead(remapData)
	, RleBlitterTransZRemapXlatZRead(currentZRemap, paletteData)
	, RleBlitterTransRemapXlatZRead75(remapData, paletteData)
	, RleBlitterTransRemapXlatZRead50(remapData, paletteData)
	, RleBlitterTransRemapXlatZRead25(remapData, paletteData)
	, RleBlitterTransXlatZReadWrite(paletteData)
	, RleBlitterTransRemapDestZReadWrite(remapData)
	, RleBlitterTransZRemapXlatZReadWrite(currentZRemap, paletteData)
	, RleBlitterTransRemapXlatZReadWrite75(remapData, paletteData)
	, RleBlitterTransRemapXlatZReadWrite50(remapData, paletteData)
	, RleBlitterTransRemapXlatZReadWrite25(remapData, paletteData)
{
}
