#include "BlitterPack.word.avx2.h"

BlitterPack16AVX2::BlitterPack16AVX2(WORD* paletteData, WORD* fullColorData, BYTE** currentZRemap, WORD halfTranslucencyMask, WORD quatTranslucencyMask, int shadeCount)
	: BlitterPlainXlat(paletteData)
	, BlitterTransXlat(paletteData)
	, BlitterTransDarken(halfTranslucencyMask)
	, BlitterTransZRemapXlat(currentZRemap, paletteData)
	, BlitterTransLucent75(paletteData, quatTranslucencyMask)
	, BlitterTransLucent50(paletteData, halfTranslucencyMask)
	, BlitterTransLucent25(paletteData, quatTranslucencyMask)
	, BlitterPlainXlatZRead(paletteData)
	, BlitterTransXlatZRead(paletteData)
	, BlitterTransDarkenZRead(halfTranslucencyMask)
	, BlitterTransZRemapXlatZRead(currentZRemap, paletteData)
	, BlitterTransLucent75ZRead(paletteData, quatTranslucencyMask)
	, BlitterTransLucent50ZRead(paletteData, halfTranslucencyMask)
	, BlitterTransLucent25ZRead(paletteData, quatTranslucencyMask)
	, BlitterTransLucent75ZReadWarp(paletteData, quatTranslucencyMask)
	, BlitterTransLucent50ZReadWarp(paletteData, halfTranslucencyMask)
	, BlitterTransLucent25ZReadWarp(paletteData, quatTranslucencyMask)
	, BlitterPlainXlatZReadWrite(paletteData)
	, BlitterTransXlatZReadWrite(paletteData)
	, BlitterTransDarkenZReadWrite(halfTranslucencyMask)
	, BlitterTransZRemapXlatZReadWrite(currentZRemap, paletteData)
	, BlitterTransLucent75ZReadWrite(paletteData, quatTranslucencyMask)
	, BlitterTransLucent50ZReadWrite(paletteData, halfTranslucencyMask)
	, BlitterTransLucent25ZReadWrite(paletteData, quatTranslucencyMask)
	, BlitterPlainXlatAlpha(fullColorData, shadeCount)
	, BlitterTransXlatAlpha(fullColorData, shadeCount)
	, BlitterTransZRemapXlatAlpha(currentZRemap, fullColorData, shadeCount)
	, BlitterTransLucent75Alpha(fullColorData, quatTranslucencyMask, shadeCount)
	, BlitterTransLucent50Alpha(fullColorData, halfTranslucencyMask, shadeCount)
	, BlitterTransLucent25Alpha(fullColorData, quatTranslucencyMask, shadeCount)
	, BlitterTransXlatWriteAlpha()
	, BlitterTransXlatMultWriteAlpha()
	, BlitterTranslucentWriteAlpha(fullColorData)
	, BlitterTranslucent50NonzeroAlpha(paletteData, halfTranslucencyMask)
	, BlitterTranslucent50ZeroAlpha(paletteData, halfTranslucencyMask)
	, BlitterPlainXlatAlphaZReadSeed(fullColorData, shadeCount)
	, BlitterTransXlatAlphaZRead(fullColorData, shadeCount)
	, BlitterTransZRemapXlatAlphaZRead(currentZRemap, fullColorData, shadeCount)
	, BlitterTransLucent75AlphaZRead(fullColorData, quatTranslucencyMask, shadeCount)
	, BlitterTransLucent50AlphaZRead(fullColorData, halfTranslucencyMask, shadeCount)
	, BlitterTransLucent25AlphaZRead(fullColorData, quatTranslucencyMask, shadeCount)
	, BlitterTransLucent75AlphaZReadWarp(fullColorData, quatTranslucencyMask, shadeCount)
	, BlitterTransLucent50AlphaZReadWarp(fullColorData, halfTranslucencyMask, shadeCount)
	, BlitterTransLucent25AlphaZReadWarp(fullColorData, quatTranslucencyMask, shadeCount)
	, BlitterPlainXlatAlphaZReadWriteSeed(fullColorData, shadeCount)
	, BlitterTransXlatAlphaZReadWrite(fullColorData, shadeCount)
	, BlitterTransZRemapXlatAlphaZReadWrite(currentZRemap, fullColorData, shadeCount)
	, BlitterTransLucent75AlphaZReadWrite(fullColorData, quatTranslucencyMask, shadeCount)
	, BlitterTransLucent50AlphaZReadWrite(fullColorData, halfTranslucencyMask, shadeCount)
	, BlitterTransLucent25AlphaZReadWrite(fullColorData, quatTranslucencyMask, shadeCount)
	, RleBlitterTransXlat(paletteData)
	, RleBlitterTransDarken(halfTranslucencyMask)
	, RleBlitterTransZRemapXlat(currentZRemap, paletteData)
	, RleBlitterTransLucent75(paletteData, quatTranslucencyMask)
	, RleBlitterTransLucent50(paletteData, halfTranslucencyMask)
	, RleBlitterTransLucent25(paletteData, quatTranslucencyMask)
	, RleBlitterTransXlatZRead(paletteData)
	, RleBlitterTransZRemapXlatZRead(currentZRemap, paletteData)
	, RleBlitterTransDarkenZRead(halfTranslucencyMask)
	, RleBlitterTransLucent75ZRead(paletteData, quatTranslucencyMask)
	, RleBlitterTransLucent50ZRead(paletteData, halfTranslucencyMask)
	, RleBlitterTransLucent25ZRead(paletteData, quatTranslucencyMask)
	, RleBlitterTransLucent75ZReadWarp(paletteData, quatTranslucencyMask)
	, RleBlitterTransLucent50ZReadWarp(paletteData, halfTranslucencyMask)
	, RleBlitterTransLucent25ZReadWarp(paletteData, quatTranslucencyMask)
	, RleBlitterTransXlatZReadWrite(paletteData)
	, RleBlitterTransZRemapXlatZReadWrite(currentZRemap, paletteData)
	, RleBlitterTransDarkenZReadWrite(halfTranslucencyMask)
	, RleBlitterTransLucent75ZReadWrite(paletteData, quatTranslucencyMask)
	, RleBlitterTransLucent50ZReadWrite(paletteData, halfTranslucencyMask)
	, RleBlitterTransLucent25ZReadWrite(paletteData, quatTranslucencyMask)
	, RleBlitterTransXlatAlpha(fullColorData, shadeCount)
	, RleBlitterTransZRemapXlatAlpha(currentZRemap, fullColorData, shadeCount)
	, RleBlitterTransLucent75Alpha(fullColorData, quatTranslucencyMask, shadeCount)
	, RleBlitterTransLucent50Alpha(fullColorData, halfTranslucencyMask, shadeCount)
	, RleBlitterTransLucent25Alpha(fullColorData, quatTranslucencyMask, shadeCount)
	, RleBlitterTransXlatAlphaZRead(fullColorData, shadeCount)
	, RleBlitterTransZRemapXlatAlphaZRead(currentZRemap, fullColorData, shadeCount)
	, RleBlitterTransLucent75AlphaZRead(fullColorData, quatTranslucencyMask, shadeCount)
	, RleBlitterTransLucent50AlphaZRead(fullColorData, halfTranslucencyMask, shadeCount)
	, RleBlitterTransLucent25AlphaZRead(fullColorData, quatTranslucencyMask, shadeCount)
	, RleBlitterTransLucent75AlphaZReadWarp(fullColorData, quatTranslucencyMask, shadeCount)
	, RleBlitterTransLucent50AlphaZReadWarp(fullColorData, halfTranslucencyMask, shadeCount)
	, RleBlitterTransLucent25AlphaZReadWarp(fullColorData, quatTranslucencyMask, shadeCount)
	, RleBlitterTransXlatAlphaZReadWrite(fullColorData, shadeCount)
	, RleBlitterTransZRemapXlatAlphaZReadWrite(currentZRemap, fullColorData, shadeCount)
	, RleBlitterTransLucent75AlphaZReadWrite(fullColorData, quatTranslucencyMask, shadeCount)
	, RleBlitterTransLucent50AlphaZReadWrite(fullColorData, halfTranslucencyMask, shadeCount)
	, RleBlitterTransLucent25AlphaZReadWrite(fullColorData, quatTranslucencyMask, shadeCount)

	, RleBlitterTransLucent75AlphaZReadFix(fullColorData, quatTranslucencyMask, shadeCount)
	, RleBlitterTransLucent50AlphaZReadFix(fullColorData, halfTranslucencyMask, shadeCount)
	, RleBlitterTransLucent25AlphaZReadFix(fullColorData, quatTranslucencyMask, shadeCount)
{}
