#pragma once

#define RESHADE_VERSION_FULL 6.8.0.10
#define RESHADE_VERSION_MAJOR 6
#define RESHADE_VERSION_MINOR 8
#define RESHADE_VERSION_REVISION 0
#define RESHADE_VERSION_BUILD 10

#define RESHADE_VERSION_STRING_FILE "6.8.0.10"
#define RESHADE_VERSION_STRING_PRODUCT "6.8.0 UNOFFICIAL"
