#include <Syringe.h>

//DEFINE_DISABLE_HOOK(0x424538, Ares_AnimClass_Update_DamageDelay)
//DEFINE_DISABLE_HOOK(0x451A28, BuildingClass_PlayAnim_Destroy_replaceDestructorcall_ares)
//DEFINE_DISABLE_HOOK(0x451E40, BuildingClass_DestroyNthAnim_Destroy_replaceDestructorcall_ares)
//DEFINE_DISABLE_HOOK(0x477007, INIClass_GetSpeedType_ares)
//DEFINE_DISABLE_HOOK(0x702cfe, TechnoClass_ReceiveDamage_PreventScatter_ares)
//DEFINE_DISABLE_HOOK(0x5673A0, MapClass_RevealArea0_ares)
//DEFINE_DISABLE_HOOK(0x5678E0, MapClass_RevealArea1_ares)
//DEFINE_DISABLE_HOOK(0x567DA0, MapClass_RevealArea2_ares)

//DEFINE_DISABLE_HOOK(0x615BD3, Handle_Static_Messages_LoopingMovie_ares)

//DEFINE_DISABLE_HOOK(0x4f8440, HouseClass_Update_TogglePower_ares)

DEFINE_DISABLE_HOOK(0x41BE80, ObjectClass_DrawRadialIndicator_ares)
DEFINE_DISABLE_HOOK(0x6FC339, TechnoClass_GetFireError_OpenToppedGunnerTemporal_ares)

DEFINE_DISABLE_HOOK(0x6F5388, TechnoClass_DrawExtras_Submerged_ares)
DEFINE_DISABLE_HOOK(0x468379, BulletClass_DrawSHP_SetAnimPalette_ares)

DEFINE_DISABLE_HOOK(0x51E748, InfantryClass_GetActionOnObject_NoSelfGuardArea_ares)

DEFINE_DISABLE_HOOK(0x4d5782, FootClass_ApproachTarget_Passive_ares)

DEFINE_DISABLE_HOOK(0x5f698f, ObjectClass_GetCell_ares)

DEFINE_DISABLE_HOOK(0x629bc0, ParasiteClass_UpdateSquiddy_Culling_ares)
DEFINE_DISABLE_HOOK(0x65b5fb, RadSiteClass_Radiate_UnhardcodeSnow_ares)
DEFINE_DISABLE_HOOK(0x6b752e, SpawnManagerClass_Update_CustomMissileTakeoff_ares)
DEFINE_DISABLE_HOOK(0x6fc417, TechnoClass_CanFire_PsionicsImmune_ares)

DEFINE_DISABLE_HOOK(0x70a990, TechnoClass_DrawVeterancy_ares)
DEFINE_DISABLE_HOOK(0x71a900, TemporalClass_Update_WarpAway_ares)

DEFINE_DISABLE_HOOK(0x744216, UnitClass_UnmarkOccupationBits_ares)
DEFINE_DISABLE_HOOK(0x7441b6, UnitClass_MarkOccupationBits_ares)
DEFINE_DISABLE_HOOK(0x70cbda, TechnoClass_DealParticleDamage_ares)

DEFINE_DISABLE_HOOK(0x4D99AA, FootClass_PointerGotInvalid_Parasite_ares)

DEFINE_DISABLE_HOOK(0x47F9A4, CellClass_DrawOverlay_WallRemap_ares)

DEFINE_DISABLE_HOOK(0x5240bd, InfantryTypeClass_LoadFromINI_DamageSparks_ares)
DEFINE_DISABLE_HOOK(0x4da584, FootClass_Update_RadImmune_ares)
DEFINE_DISABLE_HOOK(0x457DB7, BuildingClass_CanBeOccupied_SpecificAssaulters_ares)
DEFINE_DISABLE_HOOK(0x5F6515, AbstractClass_Distance2DSquared_1_ares)
DEFINE_DISABLE_HOOK(0x47C8AB, CellClass_CanThisExistHere_GateOnWall_ares)

DEFINE_DISABLE_HOOK(0x52CA37, InitGame_Delay_ares)

#ifndef aaa
DEFINE_DISABLE_HOOK(0x42784B, AnimTypeClass_CTOR_ares)
DEFINE_DISABLE_HOOK(0x428EA8, AnimTypeClass_SDDTOR_ares)
DEFINE_DISABLE_HOOK(0x428970, AnimTypeClass_SaveLoad_Prefix_ares)
DEFINE_DISABLE_HOOK(0x428800, AnimTypeClass_SaveLoad_Prefix_ares)
DEFINE_DISABLE_HOOK(0x42892C, AnimTypeClass_Load_Suffix_ares)
DEFINE_DISABLE_HOOK(0x428958, AnimTypeClass_Load_Suffix_ares)
DEFINE_DISABLE_HOOK(0x42898A, AnimTypeClass_Save_Suffix_ares)
DEFINE_DISABLE_HOOK(0x4287E9, AnimTypeClass_LoadFromINI_ares)
DEFINE_DISABLE_HOOK(0x4287DC, AnimTypeClass_LoadFromINI_ares)

DEFINE_DISABLE_HOOK(0x721876, TiberiumClass_CTOR_ares)
DEFINE_DISABLE_HOOK(0x72193A, TiberiumClass_DTOR_ares)
DEFINE_DISABLE_HOOK(0x7220D0, TiberiumClass_SaveLoad_Prefix_ares)
DEFINE_DISABLE_HOOK(0x721E80, TiberiumClass_SaveLoad_Prefix_ares)
DEFINE_DISABLE_HOOK(0x72208C, TiberiumClass_Load_Suffix_ares)
DEFINE_DISABLE_HOOK(0x72212C, TiberiumClass_Save_Suffix_ares)
DEFINE_DISABLE_HOOK(0x721CDC, TiberiumClass_LoadFromINI_ares)
DEFINE_DISABLE_HOOK(0x721CE9, TiberiumClass_LoadFromINI_ares)
DEFINE_DISABLE_HOOK(0x721C7B, TiberiumClass_LoadFromINI_ares)
#endif

DEFINE_DISABLE_HOOK(0x5F4FF9, ObjectClass_Put_IsFlammable_ares)

DEFINE_DISABLE_HOOK(0x6F407D, TechnoClass_Init_1_ares);
DEFINE_DISABLE_HOOK(0x6F4103, TechnoClass_Init_2_ares);
DEFINE_DISABLE_HOOK(0x65B5FB, RadSiteClass_Radiate_UnhardcodeSnow_ares)

#ifndef aaa
DEFINE_DISABLE_HOOK(0x55afb3, LogicClass_Update_ares)
#endif

#ifndef aaa
DEFINE_DISABLE_HOOK(0x771ee9, WeaponTypeClass_CTOR_ares)
DEFINE_DISABLE_HOOK(0x7729b0, WeaponTypeClass_LoadFromINI_ares)
DEFINE_DISABLE_HOOK(0x7729c7, WeaponTypeClass_LoadFromINI_ares)
DEFINE_DISABLE_HOOK(0x7729d6, WeaponTypeClass_LoadFromINI_ares)
DEFINE_DISABLE_HOOK(0x772cd0, WeaponTypeClass_SaveLoad_Prefix_ares)
DEFINE_DISABLE_HOOK(0x772ea6, WeaponTypeClass_Load_Suffix_ares)
DEFINE_DISABLE_HOOK(0x772eb0, WeaponTypeClass_SaveLoad_Prefix_ares)
DEFINE_DISABLE_HOOK(0x772f8c, WeaponTypeClass_Save_ares)
DEFINE_DISABLE_HOOK(0x77311d, WeaponTypeClass_SDDTOR_ares)
#endif

#ifndef aaa
DEFINE_DISABLE_HOOK(0x75d1a9, WarheadTypeClass_CTOR_ares)
DEFINE_DISABLE_HOOK(0x75dea0, WarheadTypeClass_LoadFromINI_ares)
DEFINE_DISABLE_HOOK(0x75deaf, WarheadTypeClass_LoadFromINI_ares)
DEFINE_DISABLE_HOOK(0x75e0c0, WarheadTypeClass_SaveLoad_Prefix_ares)
DEFINE_DISABLE_HOOK(0x75e2ae, WarheadTypeClass_Load_Suffix_ares)
DEFINE_DISABLE_HOOK(0x75e2c0, WarheadTypeClass_SaveLoad_Prefix_ares)
DEFINE_DISABLE_HOOK(0x75e39c, WarheadTypeClass_Save_Suffix_ares)
DEFINE_DISABLE_HOOK(0x75E5C8, WarheadTypeClass_SDDTOR_ares)
#endif