#include <Syringe.h>

#pragma warning( push )
#pragma warning (disable : 4245)
#pragma warning (disable : 4838)

//DEFINE_DISABLE_HOOK(0x424538, Ares_AnimClass_Update_DamageDelay)
DEFINE_DISABLE_HOOK(0x6E232E, ActionClass_PlayAnimAt_Ares)
DEFINE_DISABLE_HOOK(0x6FC339, TechnoClass_GetFireError_OpenToppedGunnerTemporal_Ares)
DEFINE_DISABLE_HOOK(0x763226, WaveClass_DTOR_Ares)
DEFINE_DISABLE_HOOK(0x4393F2, BombClass_SDDTOR_removeUnused1_Ares)
DEFINE_DISABLE_HOOK(0x438843, BombClass_Detonate_removeUnused2_Ares)
DEFINE_DISABLE_HOOK(0x438799, BombClass_Detonate_removeUnused3_Ares)
DEFINE_DISABLE_HOOK(0x451A28, BuildingClass_PlayAnim_Destroy_replaceDestructorcall)
DEFINE_DISABLE_HOOK(0x451E40, BuildingClass_DestroyNthAnim_Destroy_replaceDestructorcall)

//DEFINE_DISABLE_HOOK(0x42784B, AnimTypeClass_CTOR)
//DEFINE_DISABLE_HOOK(0x428EA8, AnimTypeClass_SDDTOR)
//DEFINE_DISABLE_HOOK(0x428970, AnimTypeClass_SaveLoad_Prefix)
//DEFINE_DISABLE_HOOK(0x428800, AnimTypeClass_SaveLoad_Prefix)
//DEFINE_DISABLE_HOOK(0x42892C, AnimTypeClass_Load_Suffix)
//DEFINE_DISABLE_HOOK(0x428958, AnimTypeClass_Load_Suffix)
//DEFINE_DISABLE_HOOK(0x42898A, AnimTypeClass_Save_Suffix)
//DEFINE_DISABLE_HOOK(0x4287E9, AnimTypeClass_LoadFromINI)
//DEFINE_DISABLE_HOOK(0x4287DC, AnimTypeClass_LoadFromINI)
#pragma warning( pop )