#pragma once

#include <d3d12.h>

#ifndef __ID3D12CommandQueue1_FWD_DEFINED__
#define __ID3D12CommandQueue1_FWD_DEFINED__
typedef interface ID3D12CommandQueue1 ID3D12CommandQueue1;

#endif 	/* __ID3D12CommandQueue1_FWD_DEFINED__ */

typedef
enum D3D12_COMMAND_QUEUE_PROCESS_PRIORITY
{
	D3D12_COMMAND_QUEUE_PROCESS_PRIORITY_NORMAL = 0,
	D3D12_COMMAND_QUEUE_PROCESS_PRIORITY_HIGH = 1
} 	D3D12_COMMAND_QUEUE_PROCESS_PRIORITY;

typedef
enum D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY
{
	D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY_IDLE = 0,
	D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY_DEFAULT = 1,
	D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY_NORMAL_0 = 2,
	D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY_SOFT_REALTIME_0 = 18,
	D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY_SOFT_REALTIME_1 = 19,
	D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY_SOFT_REALTIME_2 = 20,
	D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY_SOFT_REALTIME_3 = 21,
	D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY_SOFT_REALTIME_4 = 22,
	D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY_SOFT_REALTIME_5 = 23,
	D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY_SOFT_REALTIME_6 = 24,
	D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY_SOFT_REALTIME_7 = 25,
	D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY_SOFT_REALTIME_8 = 26,
	D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY_SOFT_REALTIME_9 = 27,
	D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY_SOFT_REALTIME_10 = 28,
	D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY_SOFT_REALTIME_11 = 29,
	D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY_SOFT_REALTIME_12 = 30,
	D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY_SOFT_REALTIME_13 = 31,
	D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY_HARD_REALTIME = 32
} 	D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY;


#ifndef __ID3D12CommandQueue1_INTERFACE_DEFINED__
#define __ID3D12CommandQueue1_INTERFACE_DEFINED__

/* interface ID3D12CommandQueue1 */
/* [unique][local][object][uuid] */


EXTERN_C const IID IID_ID3D12CommandQueue1;

#if defined(__cplusplus) && !defined(CINTERFACE)

MIDL_INTERFACE("3a3c3165-0ee7-4b8e-a0af-6356b4c3bbb9")
ID3D12CommandQueue1 : public ID3D12CommandQueue
{
public:
	virtual HRESULT STDMETHODCALLTYPE SetProcessPriority(
		D3D12_COMMAND_QUEUE_PROCESS_PRIORITY Priority) = 0;

	virtual HRESULT STDMETHODCALLTYPE GetProcessPriority(
		D3D12_COMMAND_QUEUE_PROCESS_PRIORITY* pOutValue) = 0;

	virtual HRESULT STDMETHODCALLTYPE SetGlobalPriority(
		D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY Priority) = 0;

	virtual HRESULT STDMETHODCALLTYPE GetGlobalPriority(
		D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY* pOutValue) = 0;

};

#endif
#endif 	/* __ID3D12CommandQueue1_INTERFACE_DEFINED__ */

#ifndef __ID3D12Device15_FWD_DEFINED__
#define __ID3D12Device15_FWD_DEFINED__
typedef interface ID3D12Device15 ID3D12Device15;

#endif 	/* __ID3D12Device15_FWD_DEFINED__ */
typedef
enum D3D12_TRIM_NOTIFICATION_FLAGS
{
	D3D12_TRIM_NOTIFICATION_FLAG_NONE = 0,
	D3D12_TRIM_NOTIFICATION_FLAG_PERIODIC_TRIM = 0x1,
	D3D12_TRIM_NOTIFICATION_FLAG_RESTART_PERIODIC_TRIM = 0x2,
	D3D12_TRIM_NOTIFICATION_FLAG_TRIM_TO_BUDGET = 0x4
} 	D3D12_TRIM_NOTIFICATION_FLAGS;

DEFINE_ENUM_FLAG_OPERATORS(D3D12_TRIM_NOTIFICATION_FLAGS)
typedef struct D3D12_TRIM_NOTIFICATION
{
	void* pContext;
	D3D12_TRIM_NOTIFICATION_FLAGS Flags;
	UINT64 NumBytesToTrim;
} 	D3D12_TRIM_NOTIFICATION;

typedef void(__stdcall* D3D12_PFN_TRIM_NOTIFICATION_CALLBACK)(
	_In_  const D3D12_TRIM_NOTIFICATION* __MIDL____MIDL_itf_d3d12_0000_00640000);

typedef struct D3D12_REGISTER_TRIM_NOTIFICATION
{
	D3D12_PFN_TRIM_NOTIFICATION_CALLBACK pfnCallback;
	void* pContext;
	DWORD CallbackCookie;
} D3D12_REGISTER_TRIM_NOTIFICATION;

typedef
enum D3D12_QUERY_HEAP_FLAGS
{
	D3D12_QUERY_HEAP_FLAG_NONE = 0,
	D3D12_QUERY_HEAP_FLAG_CPU_RESOLVE = 1
} 	D3D12_QUERY_HEAP_FLAGS;

#ifndef __ID3D12Device15_INTERFACE_DEFINED__
#define __ID3D12Device15_INTERFACE_DEFINED__

/* interface ID3D12Device15 */
/* [unique][local][object][uuid] */


EXTERN_C const IID IID_ID3D12Device15;

#if defined(__cplusplus) && !defined(CINTERFACE)

MIDL_INTERFACE("76cff76f-1e9b-4450-8cdc-34f1af788e5b")
ID3D12Device15 : public ID3D12Device14
{
public:
	virtual HRESULT STDMETHODCALLTYPE RegisterTrimNotificationCallback(
		_Inout_  D3D12_REGISTER_TRIM_NOTIFICATION * pData) = 0;

	virtual HRESULT STDMETHODCALLTYPE UnregisterTrimNotificationCallback(
		DWORD CallbackCookie) = 0;

	virtual HRESULT STDMETHODCALLTYPE TryCreateShaderResourceView(
		_In_opt_  ID3D12Resource* pResource,
		_In_opt_  const D3D12_SHADER_RESOURCE_VIEW_DESC* pDesc,
		_In_  D3D12_CPU_DESCRIPTOR_HANDLE DestDescriptor) = 0;

	virtual HRESULT STDMETHODCALLTYPE TryCreateUnorderedAccessView(
		_In_opt_  ID3D12Resource* pResource,
		_In_opt_  ID3D12Resource* pCounterResource,
		_In_opt_  const D3D12_UNORDERED_ACCESS_VIEW_DESC* pDesc,
		_In_  D3D12_CPU_DESCRIPTOR_HANDLE DestDescriptor) = 0;

	virtual HRESULT STDMETHODCALLTYPE TryCreateConstantBufferView(
		_In_opt_  const D3D12_CONSTANT_BUFFER_VIEW_DESC* pDesc,
		_In_  D3D12_CPU_DESCRIPTOR_HANDLE DestDescriptor) = 0;

	virtual HRESULT STDMETHODCALLTYPE TryCreateSampler2(
		_In_  const D3D12_SAMPLER_DESC2* pDesc,
		_In_  D3D12_CPU_DESCRIPTOR_HANDLE DestDescriptor) = 0;

	virtual HRESULT STDMETHODCALLTYPE TryCreateRenderTargetView(
		_In_opt_  ID3D12Resource* pResource,
		_In_opt_  const D3D12_RENDER_TARGET_VIEW_DESC* pDesc,
		_In_  D3D12_CPU_DESCRIPTOR_HANDLE DestDescriptor) = 0;

	virtual HRESULT STDMETHODCALLTYPE TryCreateDepthStencilView(
		_In_opt_  ID3D12Resource* pResource,
		_In_opt_  const D3D12_DEPTH_STENCIL_VIEW_DESC* pDesc,
		_In_  D3D12_CPU_DESCRIPTOR_HANDLE DestDescriptor) = 0;

	virtual HRESULT STDMETHODCALLTYPE TryCreateSamplerFeedbackUnorderedAccessView(
		_In_opt_  ID3D12Resource* pTargetedResource,
		_In_opt_  ID3D12Resource* pFeedbackResource,
		_In_  D3D12_CPU_DESCRIPTOR_HANDLE DestDescriptor) = 0;

	virtual HRESULT STDMETHODCALLTYPE CreateQueryHeap1(
		_In_  const D3D12_QUERY_HEAP_DESC* pDesc,
		_In_  D3D12_QUERY_HEAP_FLAGS Flags,
		_In_  REFIID riid,
		_COM_Outptr_  void** ppvHeap) = 0;

	virtual HRESULT STDMETHODCALLTYPE ResolveQueryData(
		_In_  ID3D12QueryHeap* pQueryHeap,
		_In_  D3D12_QUERY_TYPE Type,
		_In_  UINT StartIndex,
		_In_  UINT NumQueries,
		_Inout_  void* pResolvedQueryData) = 0;

};

#endif
#endif