#include "AircraftClass.h"

DEFINE_IMPLEMENTATION(HRESULT STDMETHODCALLTYPE AircraftClass::QueryInterface(REFIID, LPVOID*), 0x414290);
DEFINE_IMPLEMENTATION(ULONG STDMETHODCALLTYPE AircraftClass::AddRef(), 0x4142F0);
DEFINE_IMPLEMENTATION(ULONG STDMETHODCALLTYPE AircraftClass::Release(), 0x414300);
DEFINE_IMPLEMENTATION(LONG STDMETHODCALLTYPE AircraftClass::GetClassID(CLSID*), 0x41C190);
DEFINE_IMPLEMENTATION(HRESULT STDMETHODCALLTYPE AircraftClass::Load(IStream*), 0x41B430);
DEFINE_IMPLEMENTATION(HRESULT STDMETHODCALLTYPE AircraftClass::Save(IStream*, BOOL), 0x41B5C0);
DEFINE_IMPLEMENTATION(LONG AircraftClass::Landing_Altitude(), 0x41B6A0);
DEFINE_IMPLEMENTATION(LONG AircraftClass::Landing_Direction(), 0x41B760);
DEFINE_IMPLEMENTATION(BOOL AircraftClass::Is_Loaded(), 0x41B7D0);
DEFINE_IMPLEMENTATION(LONG AircraftClass::Is_Strafe(), 0x41B7F0);
DEFINE_IMPLEMENTATION(LONG AircraftClass::Is_Fighter(), 0x41B840);
DEFINE_IMPLEMENTATION(LONG AircraftClass::Is_Locked(), 0x41B860);