#include "CStreamClass.h"
#include <ASMMacros.h>

DEFINE_IMPLEMENTATION(HRESULT CStreamClass::QueryInterface(REFIID, LPVOID*), 0x4A2990);
DEFINE_IMPLEMENTATION(ULONG CStreamClass::AddRef(), 0x4A2930);
DEFINE_IMPLEMENTATION(ULONG CStreamClass::Release(), 0x4A2950);
DEFINE_IMPLEMENTATION(HRESULT CStreamClass::Read(void*, ULONG, ULONG*), 0x4A2B60);
DEFINE_IMPLEMENTATION(HRESULT CStreamClass::Write(const void*, ULONG, ULONG*), 0x4A2CD0);
DEFINE_IMPLEMENTATION(HRESULT CStreamClass::Seek(LARGE_INTEGER, DWORD, ULARGE_INTEGER*), 0x4A2E00);
DEFINE_IMPLEMENTATION(HRESULT CStreamClass::SetSize(ULARGE_INTEGER), 0x4A2E50);
DEFINE_IMPLEMENTATION(HRESULT CStreamClass::CopyTo(IStream*, ULARGE_INTEGER, ULARGE_INTEGER*, ULARGE_INTEGER*), 0x4A2EA0);
DEFINE_IMPLEMENTATION(HRESULT CStreamClass::Commit(DWORD), 0x4A2EE0);
DEFINE_IMPLEMENTATION(HRESULT CStreamClass::Revert(), 0x4A2F10);
DEFINE_IMPLEMENTATION(HRESULT CStreamClass::LockRegion(ULARGE_INTEGER, ULARGE_INTEGER, DWORD), 0x4A2F40);
DEFINE_IMPLEMENTATION(HRESULT CStreamClass::UnlockRegion(ULARGE_INTEGER, ULARGE_INTEGER, DWORD), 0x4A2F80);
DEFINE_IMPLEMENTATION(HRESULT CStreamClass::Stat(STATSTG*, DWORD), 0x4A2FC0);
DEFINE_IMPLEMENTATION(HRESULT CStreamClass::Clone(IStream**), 0x4A2FF0);
DEFINE_IMPLEMENTATION(HRESULT CStreamClass::Link_Stream(IUnknown*), 0x4A2A20);
DEFINE_IMPLEMENTATION(HRESULT CStreamClass::Unlink_Stream(IUnknown**), 0x4A2AB0);

CStreamClass::CStreamClass()
{
	JMP_THIS(0x4A2820);
}

CStreamClass::~CStreamClass()
{
	JMP_THIS(0x4A2880);
}

DEFINE_IMPLEMENTATION(HRESULT CStreamClass::Compress(void*, ULONG), 0x4A3020);
DEFINE_IMPLEMENTATION(HRESULT CStreamClass::Compress(), 0x4A30E0);
